PRAGMA foreign_keys = ON;

CREATE TABLE pets (
    postid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    petname VARCHAR(20) NOT NULL,
    info VARCHAR(1024) NOT NULL,
    petfilename VARCHAR(64) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
);